export const API_SUCCESS_CODE: Record<string, number> = {
  // AUTH
  SIGN_UP_SUCCESS: 200,
  REFRESH_TOKEN_SUCCESS: 200,
  LOGIN_SUCCESS: 200,
  INTROSPECT_TOKEN_SUCCESS: 200,
  LOGOUT_SUCCESS: 200,
  FORGET_PASSWORD_SUCCESS: 200,
  RESET_PASSWORD_SUCCESS: 200,

  // USER
  GET_CURRENT_USER_PROFILE_SUCCESS: 1000,
  CHANGE_PASSWORD_SUCCESS: 200,

  // USER PROFILE
  CREATE_OR_UPDATE_USER_PROFILE_SUCCESS: 200,

  // ADDRESS
  CREATE_ADDRESS_SUCCESS: 0,
  UPDATE_ADDRESS_SUCCESS: 0,
  DELETE_ADDRESS_SUCCESS: 200,
  SET_DEFAULT_ADDRESS_SUCCESS: 0,

  // CART
  ADD_ITEM_TO_CART_SUCCESS: 200,
  UPDATE_ITEM_IN_CART_SUCCESS: 200,
  REMOVE_ITEM_FROM_CART_SUCCESS: 200,

  // ORDER
  PLACE_ORDER_SUCCESS: 200,
  GET_ORDERS_BY_PROFILE_ID_SUCCESS: 200,
  UPDATE_ORDER_ADDRESS_SUCCESS: 200,
  CANCEL_ORDER_ADDRESS_SUCCESS: 200,

  // PRODUCT
  ADD_PRODUCT_SUCCESS: 200,
  UPDATE_PRODUCT_SUCCESS: 200,
  DELETE_PRODUCT_SUCCESS: 200,

  //CATEGORY
  ADD_CATEGORY_SUCCESS: 200,
  UPDATE_CATEGORY_SUCCESS: 200,
  DELETE_CATEGORY_SUCCESS: 200,
};
