type productItemProps = {
  id: string;
  productName: string;
  categories: string;
  price: string;
  quantity: string;
  status: "Chờ xử lý" | "Đang xử lý" | "Thành công" | "Thất bại";
};

export const productLists: productItemProps[] = [
  {
    id: "a1f9c3d2",
    productName: "Cây Lưỡi Hổ",
    categories: "Trong nhà",
    price: "150000",
    quantity: "5",
    status: "Thành công",
  },
  {
    id: "b4e7d8f1",
    productName: "Cây Trầu Bà Leo",
    categories: "Trong nhà",
    price: "120000",
    quantity: "8",
    status: "Đang xử lý",
  },
  {
    id: "c9f1a3b8",
    productName: "Cây Phát Tài",
    categories: "Trong nhà",
    price: "250000",
    quantity: "4",
    status: "Chờ xử lý",
  },
  {
    id: "d3a8c4f7",
    productName: "Cây Sen Đá Mix",
    categories: "Trong nhà",
    price: "60000",
    quantity: "12",
    status: "Thất bại",
  },
  {
    id: "e7b2f9c1",
    productName: "Cây Xương Rồng Tròn",
    categories: "Trong nhà",
    price: "90000",
    quantity: "10",
    status: "Thành công",
  },

  {
    id: "f2c4d8e9",
    productName: "Cây Hoa Giấy",
    categories: "Ngoài trời",
    price: "180000",
    quantity: "6",
    status: "Đang xử lý",
  },
  {
    id: "g8e1a9c3",
    productName: "Cây Bàng Singapore",
    categories: "Ngoài trời",
    price: "450000",
    quantity: "2",
    status: "Chờ xử lý",
  },
  {
    id: "h5d7b2f1",
    productName: "Cây Sứ Đại",
    categories: "Ngoài trời",
    price: "350000",
    quantity: "3",
    status: "Thành công",
  },
  {
    id: "i3f9c6a8",
    productName: "Cây Dừa Cảnh Mini",
    categories: "Ngoài trời",
    price: "200000",
    quantity: "7",
    status: "Thất bại",
  },
  {
    id: "j9a6e3b2",
    productName: "Cây Mai Vàng Giống",
    categories: "Ngoài trời",
    price: "600000",
    quantity: "2",
    status: "Thành công",
  },

  {
    id: "k4c8f1d9",
    productName: "Hạt Giống Rau Muống",
    categories: "Hạt giống",
    price: "20000",
    quantity: "25",
    status: "Thành công",
  },
  {
    id: "l7e2b6a1",
    productName: "Hạt Giống Cà Chua F1",
    categories: "Hạt giống",
    price: "35000",
    quantity: "18",
    status: "Chờ xử lý",
  },
  {
    id: "m1f9d8e4",
    productName: "Hạt Giống Dưa Leo",
    categories: "Hạt giống",
    price: "30000",
    quantity: "30",
    status: "Đang xử lý",
  },
  {
    id: "n5a3c7f2",
    productName: "Hạt Giống Hoa Cúc",
    categories: "Hạt giống",
    price: "25000",
    quantity: "20",
    status: "Thất bại",
  },
  {
    id: "o2e9b1d8",
    productName: "Hạt Giống Rau Xà Lách",
    categories: "Hạt giống",
    price: "28000",
    quantity: "22",
    status: "Thành công",
  },

  {
    id: "p3c7d5e1",
    productName: "Bình Tưới Cây 1.5L",
    categories: "Dụng cụ làm vườn",
    price: "50000",
    quantity: "10",
    status: "Đang xử lý",
  },
  {
    id: "q8f2b6a9",
    productName: "Xẻng Làm Vườn Mini",
    categories: "Dụng cụ làm vườn",
    price: "40000",
    quantity: "12",
    status: "Chờ xử lý",
  },
  {
    id: "r6a1e9c3",
    productName: "Bộ Cuốc - Xẻng Mini",
    categories: "Dụng cụ làm vườn",
    price: "90000",
    quantity: "6",
    status: "Thành công",
  },
  {
    id: "s9d3c2f8",
    productName: "Găng Tay Làm Vườn",
    categories: "Dụng cụ làm vườn",
    price: "30000",
    quantity: "20",
    status: "Thành công",
  },
  {
    id: "t7e4a9b1",
    productName: "Kéo Tỉa Cành",
    categories: "Dụng cụ làm vườn",
    price: "120000",
    quantity: "5",
    status: "Thất bại",
  },

  {
    id: "u1f8c3d7",
    productName: "Chậu Gốm Tráng Men",
    categories: "Vật trang trí",
    price: "150000",
    quantity: "8",
    status: "Đang xử lý",
  },
  {
    id: "v6a9e2f3",
    productName: "Chậu Xi Măng Mini",
    categories: "Vật trang trí",
    price: "70000",
    quantity: "10",
    status: "Thành công",
  },
  {
    id: "w3d7b1c9",
    productName: "Cây Giả Trang Trí Mini",
    categories: "Vật trang trí",
    price: "90000",
    quantity: "7",
    status: "Chờ xử lý",
  },
  {
    id: "x8e4c2a1",
    productName: "Đèn UV Trang Trí Cây",
    categories: "Vật trang trí",
    price: "200000",
    quantity: "3",
    status: "Thất bại",
  },
  {
    id: "y4b9f7d2",
    productName: "Bộ Sỏi Trang Trí",
    categories: "Vật trang trí",
    price: "30000",
    quantity: "15",
    status: "Thành công",
  },

  {
    id: "z3f8c6a1",
    productName: "Cây Kim Tiền",
    categories: "Trong nhà",
    price: "350000",
    quantity: "4",
    status: "Đang xử lý",
  },
  {
    id: "a7c1b9e3",
    productName: "Cây Ngọc Ngân",
    categories: "Trong nhà",
    price: "180000",
    quantity: "6",
    status: "Thành công",
  },
  {
    id: "b9e4d2f7",
    productName: "Cây Trầu Bà Nam Mỹ",
    categories: "Trong nhà",
    price: "200000",
    quantity: "5",
    status: "Chờ xử lý",
  },
  {
    id: "c6a3f7d1",
    productName: "Cây Dương Xỉ",
    categories: "Trong nhà",
    price: "90000",
    quantity: "8",
    status: "Thất bại",
  },
  {
    id: "d4f9b1e2",
    productName: "Cây Hạnh Phúc",
    categories: "Trong nhà",
    price: "400000",
    quantity: "3",
    status: "Thành công",
  },

  {
    id: "e1b7c3d9",
    productName: "Cây Sấu Công Trình",
    categories: "Ngoài trời",
    price: "250000",
    quantity: "4",
    status: "Đang xử lý",
  },
  {
    id: "f9e2a8b1",
    productName: "Cây Sala",
    categories: "Ngoài trời",
    price: "700000",
    quantity: "2",
    status: "Thành công",
  },
  {
    id: "g4c1d7e8",
    productName: "Cây Lộc Vừng",
    categories: "Ngoài trời",
    price: "550000",
    quantity: "2",
    status: "Chờ xử lý",
  },
  {
    id: "h6f3a9c2",
    productName: "Cây Sứ Thái",
    categories: "Ngoài trời",
    price: "180000",
    quantity: "7",
    status: "Thất bại",
  },
  {
    id: "i1a9b4d3",
    productName: "Cây Ổi Giống",
    categories: "Ngoài trời",
    price: "120000",
    quantity: "9",
    status: "Thành công",
  },

  {
    id: "j5d2c8f7",
    productName: "Hạt Giống Dưa Hấu",
    categories: "Hạt giống",
    price: "35000",
    quantity: "18",
    status: "Đang xử lý",
  },
  {
    id: "k3f8e1b9",
    productName: "Hạt Giống Ớt Chỉ Thiên",
    categories: "Hạt giống",
    price: "28000",
    quantity: "24",
    status: "Thành công",
  },
  {
    id: "l8a1d6e3",
    productName: "Hạt Giống Bầu Sao",
    categories: "Hạt giống",
    price: "25000",
    quantity: "21",
    status: "Thất bại",
  },
  {
    id: "m4e7b9c1",
    productName: "Hạt Giống Hoa Hồng Leo",
    categories: "Hạt giống",
    price: "45000",
    quantity: "12",
    status: "Chờ xử lý",
  },
  {
    id: "n2c9f6a4",
    productName: "Hạt Giống Bí Ngòi",
    categories: "Hạt giống",
    price: "30000",
    quantity: "26",
    status: "Thành công",
  },

  {
    id: "o7b3e1f8",
    productName: "Cuốc Làm Vườn Lớn",
    categories: "Dụng cụ làm vườn",
    price: "150000",
    quantity: "4",
    status: "Đang xử lý",
  },
  {
    id: "p1f6c8d2",
    productName: "Bình Xịt Tưới Cây 2L",
    categories: "Dụng cụ làm vườn",
    price: "85000",
    quantity: "6",
    status: "Thành công",
  },
  {
    id: "q4d9b1e7",
    productName: "Xô Tưới Hoa",
    categories: "Dụng cụ làm vườn",
    price: "40000",
    quantity: "10",
    status: "Chờ xử lý",
  },
  {
    id: "r8a2f7c3",
    productName: "Bộ Dao Gọt Cây Bonsai",
    categories: "Dụng cụ làm vườn",
    price: "230000",
    quantity: "3",
    status: "Thất bại",
  },
  {
    id: "s6c1e8b9",
    productName: "Kéo Cắt Cành Cao Cấp",
    categories: "Dụng cụ làm vườn",
    price: "150000",
    quantity: "5",
    status: "Thành công",
  },
];
